sonar.projectKey=Team-Haruki_Haruki-Nuverse-StructTool
sonar.organization=team-haruki
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=data/**,**/*_test.go,python/tests/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go,python/tests/**
sonar.go.coverage.reportPaths=coverage.out
sonar.python.coverage.reportPaths=python/coverage.xml
